global:
  scrape_interval: 5s # Jak często pobierać dane

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'backend-spring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend:8080']

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'minio'
    metrics_path: '/minio/v2/metrics/cluster'
    scheme: http
    static_configs:
      - targets: ['minio:9000']

  - job_name: 'keycloak'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['keycloak:9000']